---
deployment:
  tasks:
    - export DEPLOYPATH=/home/churchandsermons
    - /bin/cp -r * $DEPLOYPATH/testing/ #copy all from root
    - /bin/cp -r ./public/* $DEPLOYPATH/testing.churchandsermons.com/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/testing.churchandsermons.com/js/
    - /bin/cp ./public/css/*.css $DEPLOYPATH/testing.churchandsermons.com/css/
